---
- name: Unmount {{ backup_volume_name }}
  become: yes
  ansible.posix.mount:
    path: /mnt/backup
    src: LABEL={{ backup_volume_name }}
    fstype: btrfs
    state: unmounted
  changed_when: false

- name: Mount {{ backup_volume_name }}
  become: yes
  ansible.posix.mount:
    path: /mnt/backup
    src: LABEL={{ backup_volume_name }}
    fstype: btrfs
    state: ephemeral
  changed_when: false
